name: Deploy Lambda (Dev & Prod)

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Package Lambda code
        run: |
          cd src
          zip -r ../code.zip .

      - name: Deploy to AWS Lambda
        run: |
          if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            FUNCTION_NAME="arn:aws:lambda:us-west-1:773037794134:function:test1-dev"
          else
            FUNCTION_NAME="arn:aws:lambda:us-west-1:773037794134:function:test1-prod"
          fi

          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://code.zip